services:
  # 1. MySQL 서비스
  db:
    image: mysql:8.0
    container_name: yeondeung-mysql
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - yeondeung-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # 2. Redis 서비스
  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - yeondeung-net

  # 3. YEONDEUNG-BE 앱 서비스
  app:
    build: 
      context: ./backend           # Dockerfile이 있는 위치 (현재 폴더)
      dockerfile: Dockerfile
    image: ${DOCKER_USER}/yeondeung-be:latest
    container_name: yeondeung-app
    depends_on:
      db:
        condition: service_healthy
      elasticsearch:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - yeondeung-net
      - elk-net
    environment:
      NODE_ENV: 'production'
      DB_HOST: 'db'
      ELASTICSEARCH_NODE: 'http://elasticsearch:9200'
      REDIS_HOST: 'redis'
    env_file:
      - .env

  # 4. Elasticsearch
  elasticsearch:
    build:
      context: ./elasticsearch 
      dockerfile: Dockerfile
    image: ${DOCKER_USER}/yeondeung-es:latest
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - elk-net

  # 5. Kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elk-net

volumes:
  mysql-data:

networks:
  elk-net:
    driver: bridge
  yeondeung-net:
    driver: bridge